### ISSUE TITLE
account scoping question

### ISSUE THREAD

**Issue by FineLineAutomation** [radar/saas_book_examples#9]
I am going through the book and am at the part where you're scoping application models by account.

In section 3.1, you say to create an active record extension:

![image1-1](https://cloud.githubusercontent.com/assets/2739249/10098370/ed246e8c-634e-11e5-83e1-695d1315c232.PNG)

But in the blorgh integration in 4.5 you use the scoped_to method.

![image1-2](https://cloud.githubusercontent.com/assets/2739249/10098382/0096ba60-634f-11e5-89c2-1812d6ddf0bd.PNG)

Which is preferred? I am using database fields instead of Apartment for this app.

On another note, why wouldn't we just use a default scope? Something like:

default_scope lambda {
 if current_accont.nil?
   raise Errors::NoAccountSet
 end

 where(:account_id => current_account.id)
}

**Comment by radar** [comment]
I'm actually shying away from this type of thing in the second edition. What I'd prefer to do is just have the `Account` model exist within the application and then have it define the associations. In the second edition, it's as simple as `account.books`.

If you're going with the engine route, then that's where I would use the `scoped_to` method. 

---

We can't use a `default_scope` in the model because the model has no idea what the `current_account` would be; it's only the controller that knows about that, because the controller knows about the current request. The model has no such knowledge.

**Comment by FineLineAutomation** [comment]
So, instead of the scoped_to_account method your would just create an account model in the application and put the associations in there manually?

**Comment by radar** [comment]
Yes, that's right.

**Comment by FineLineAutomation** [comment]
Thanks. You should make that clearer in the book. I am not sure if you changed it in the apartment section but I totally skipped over that part and was all confused when the code changed.

**Comment by radar** [comment]
It'll be clearer in the second edition because I don't have the `scoped_to` method at all. I just use associations for the `Account` model which exists within the application.
